### PR TITLE
Fix dragging issue on frameless window

### PR DESCRIPTION
**Pull request by mimeosd**
Close button was overlapping other widgets and thus interferring with mouseDrag thus preventing widget to be dragged around.

### CODE REVIEW

**Comment by mimeosd** [comment]
Sorry for forgetting to add my .venv folder to .gitignore.... :(

**Comment by PerseusKyogre09** [comment]
Hey, can you raise the PR again without the .venv folder?
Also I've tested your code from your fork, and the dragging works perfectly! Could you please try to see if you could keep the original functionalities like the custom Text, different text sizes and minimize to tray (it exits the loop in the code, which is originally expected to be in the tray menu options)? If the drag feature stops working because of them, do inform I'll try to look into the fix!

**Comment by mimeosd** [comment]
Sure do will take a look tomorrow.

**Comment by mimeosd** [comment]
Removed .venv folder from pr.
Will work on fixes you asked for.

**Comment by mimeosd** [comment]
Added another commit for stuff you asked. I also created you a possible_solution.py file so you can check it out (separate QLabels and update them one by one). I am not so advanced to know why HTML makes issues so I gave my best lol. 👯‍♂️

**Review by PerseusKyogre09 — APPROVED** [review]
Yeah... HTML appears to be the issue
and possible_solutions.py also makes the window undraggable
so I'll see if I can fix it or not

**Pull request merged**
